const { isLogin } = require("../Controllers/auth");
const { createGroup, fetchGroups, addMebmerToGroup, groupDetails, isOwner, AcceptRequest, fetchPendingRequest } = require("../Controllers/group");
let router = require("express").Router();
router.post("/create",isLogin,createGroup);
router.post("/get",isLogin,fetchGroups);
router.post("/addMember",isLogin,addMebmerToGroup);
router.post("/groupDetails",isLogin,isOwner,groupDetails);
router.post("/acceptRequest",isLogin,AcceptRequest);
router.post("/pendingRequests",isLogin,fetchPendingRequest);
module.exports = router;